apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - redis/statefulset.yaml
  - redis/service.yaml
  - rabbitmq/statefulset.yaml
  - rabbitmq/service.yaml
  - api/deployment.yaml
  - api/service.yaml
  - worker/deployment.yaml
  - web/deployment.yaml
  - web/service.yaml
  - ingress.yaml
